# Generated by Django 5.2.12 on 2026-03-28 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'قسم', 'verbose_name_plural': 'الأقسام'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'منتج', 'verbose_name_plural': 'المنتجات'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'صورة منتج', 'verbose_name_plural': 'صور المنتجات'},
        ),
        migrations.AlterModelOptions(
            name='variant',
            options={'ordering': ['product', 'size', 'color'], 'verbose_name': 'متغير', 'verbose_name_plural': 'المتغيرات'},
        ),
    ]
