# Generated by Django 5.2.12 on 2026-03-29 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_extra_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_percent',
        ),
        migrations.AlterField(
            model_name='product',
            name='price_dzd',
            field=models.PositiveIntegerField(verbose_name='السعر'),
        ),
    ]
