# Generated by Django 5.2.12 on 2026-04-01 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_category'),
        ('store', '0006_product_slug_optional'),
    ]

    operations = [
    ]
