# Generated by Django 5.2.13 on 2026-04-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_merge_20260402_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='color_image',
            field=models.ImageField(blank=True, null=True, upload_to='variants/%Y/%m/', verbose_name='صورة اللون'),
        ),
    ]
