# Generated by Django 5.2.13 on 2026-04-24 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_variant_color_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='color',
            field=models.CharField(max_length=50, verbose_name='اللون'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='size',
            field=models.CharField(blank=True, choices=[('STD', 'مقاس موحد'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default='STD', max_length=5, verbose_name='المقاس'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='المخزون'),
        ),
    ]
