# Generated by Django 5.2.13 on 2026-04-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_variant_color_alter_variant_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='color_image',
            field=models.ImageField(blank=True, null=True, upload_to='variants/', verbose_name='صورة اللون'),
        ),
    ]
