# Generated by Django 5.2.13 on 2026-04-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_productimage_image_alter_variant_color_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='static/products/'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='color_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/variants/', verbose_name='صورة اللون'),
        ),
    ]
