# Generated by Django 5.2.13 on 2026-04-30 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_productimage_image_alter_variant_color_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['-is_primary', 'id'], 'verbose_name': 'صورة منتج', 'verbose_name_plural': 'صور المنتجات'},
        ),
    ]
