# Generated by Django 5.2.12 on 2026-03-28 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'رأي زبونة', 'verbose_name_plural': 'آراء الزبونات'},
        ),
        migrations.AlterModelOptions(
            name='storesettings',
            options={'verbose_name': 'إعدادات المتجر', 'verbose_name_plural': 'إعدادات المتجر'},
        ),
    ]
