# Generated by Django 5.2.12 on 2026-03-28 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'طلب', 'verbose_name_plural': 'الطلبات'},
        ),
        migrations.AlterModelOptions(
            name='orderstatushistory',
            options={'ordering': ['changed_at'], 'verbose_name': 'سجل حالة الطلب', 'verbose_name_plural': 'سجل حالات الطلب'},
        ),
    ]
