# Generated by Django 5.2.12 on 2026-03-30 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_options_alter_orderstatushistory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'جديد'), ('PENDING_CONFIRMATION', 'قيد التأكيد'), ('CONFIRMED', 'تم التأكيد'), ('PREPARING', 'قيد التحضير'), ('SHIPPED', 'تم الشحن'), ('OUT_FOR_DELIVERY', 'قيد التوصيل'), ('DELIVERED', 'تم التسليم'), ('CANCELED', 'ملغي')], default='NEW', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='status',
            field=models.CharField(choices=[('NEW', 'جديد'), ('PENDING_CONFIRMATION', 'قيد التأكيد'), ('CONFIRMED', 'تم التأكيد'), ('PREPARING', 'قيد التحضير'), ('SHIPPED', 'تم الشحن'), ('OUT_FOR_DELIVERY', 'قيد التوصيل'), ('DELIVERED', 'تم التسليم'), ('CANCELED', 'ملغي')], max_length=30),
        ),
    ]
